blank_issues_enabled: true
contact_links:
  - name: "Apollo Discourse Community"
    url: https://community.apollographql.com/tag/server
    about: >-
      The Apollo Server tag in our Apollo Discourse Community has many existing
      questions and answers. You can see if your question has already been
      answered there or ask a new one.
  - name: "Stack Overflow tagged \"apollo\""
    url: https://stackoverflow.com/questions/tagged/apollo
    about: >-
      If you can't find what you're looking for, many questions are already
      answered on Stack Overflow.
